$schema: "https://json-schema.org/draft/2020-12/schema"
title: VAULTIS Operational Intelligence Data Schema
description: JSON schema for structured storage of AI-generated intelligence data in a secure, interoperable repository.
type: object
required:
  - record_id
  - timestamp_utc
  - classification
  - source
  - data_type
  - confidence_score
  - operational_context
  - metadata
  - data_payload
properties:
  record_id:
    type: string
    description: Unique identifier for the data record.
  timestamp_utc:
    type: string
    format: date-time
    description: UTC timestamp of data generation.
  classification:
    type: string
    enum:
      - UNCLASSIFIED
      - CONFIDENTIAL
      - SECRET
      - TOP SECRET
    description: Security classification level.
  source:
    type: object
    description: Information about the AI model and system generating the data.
    required:
      - ai_model
      - model_version
      - system_instance
    properties:
      ai_model:
        type: string
      model_version:
        type: string
      system_instance:
        type: string
  data_type:
    type: string
    description: Type/category of data (e.g., threat assessment, situational awareness).
  confidence_score:
    type: number
    minimum: 0
    maximum: 1
    description: AI-assigned confidence score for the data accuracy (0 to 1).
  operational_context:
    type: object
    description: Contextual operational details for understanding and linking.
    properties:
      mission_id:
        type: string
      location:
        type: string
      commander_id:
        type: string
    required:
      - mission_id
      - location
  metadata:
    type: object
    description: Comprehensive metadata for traceability and interoperability.
    properties:
      tags:
        type: array
        items:
          type: string
      linked_records:
        type: array
        items:
          type: string
      schema_version:
        type: string
      comments:
        type: string
    required:
      - tags
      - schema_version
  data_payload:
    type: object
    description: The structured data generated by the AI.
    additionalProperties: true
