name: Seal Commit

on:
  push:
    branches:
      - main
      - 'v*'

jobs:
  seal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Import GPG key and setup Git
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          git config user.name "Bryan A. Jewell"
          git config user.email "0009-0001-2983-0505@orcid.org"
          git config commit.gpgsign true
          git config user.signingkey "$GPG_KEY_ID"

      - name: Seal commit
        run: |
          git commit --allow-empty -S -m "Seal commit with ORCID identity"

      - name: Tag Version
        run: |
          version=$(grep '^version:' VAULTIS.yaml | cut -d':' -f2 | tr -d '[:space:]')
          git tag -a "v$version" -m "Version $version"
          git push origin --tags

      - name: Drift Analysis (Truth Vector)
        run: python3 core/drift_analysis_engine.py

      - name: Rotate Anchor
        run: python3 scripts/rotate_anchor.py

      - name: CarlAPI Ethical Scan
        env:
          CARLAPI_TOKEN: ${{ secrets.CARLAPI_TOKEN }}
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:9000/scan \
                    -H "Authorization: Bearer $CARLAPI_TOKEN")
          if [ "$status" -ne 200 ]; then
            echo "CarlAPI scan failed with HTTP status $status"
            exit 1
          fi
